#!/bin/bash
# Netdata Config Generator
# Watches Docker services for monitoring labels and generates Netdata collector configs
#
# Supported labels (under deploy.labels):
#   netdata.postgres.name=my_database
#   netdata.postgres.dsn=postgresql://user:pass@host:5432/db
#
# Uses docker service inspect to read service labels (like Traefik does).
# More collectors can be added following the same pattern.

set -e

CONFIG_DIR="/etc/netdata/go.d"
POLL_INTERVAL=${POLL_INTERVAL:-30}

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

generate_postgres_config() {
    local config_file="$CONFIG_DIR/postgres.conf"
    local temp_file=$(mktemp)
    
    echo "# Auto-generated by netdata-config-generator" > "$temp_file"
    echo "# Do not edit manually - changes will be overwritten" >> "$temp_file"
    echo "" >> "$temp_file"
    echo "jobs:" >> "$temp_file"
    
    local found_jobs=0
    
    # Get all services with netdata.postgres labels (using service inspect like Traefik)
    for service in $(docker service ls --format '{{.Name}}'); do
        local name=$(docker service inspect --format '{{index .Spec.Labels "netdata.postgres.name"}}' "$service" 2>/dev/null || echo "")
        local dsn=$(docker service inspect --format '{{index .Spec.Labels "netdata.postgres.dsn"}}' "$service" 2>/dev/null || echo "")
        
        if [[ -n "$dsn" && "$dsn" != "<no value>" ]]; then
            local job_name="${name:-postgres_$service}"
            log "Found PostgreSQL: $job_name (service: $service)"
            
            cat >> "$temp_file" << EOF
  - name: ${job_name}
    dsn: "${dsn}"
    collect_databases_matching: "*"
    max_db_tables: 50
    max_db_indexes: 250

EOF
            found_jobs=$((found_jobs + 1))
        fi
    done
    
    if [[ $found_jobs -gt 0 ]]; then
        # Only update if config changed
        if ! cmp -s "$temp_file" "$config_file" 2>/dev/null; then
            mv "$temp_file" "$config_file"
            chmod 644 "$config_file"
            log "Updated postgres.conf with $found_jobs job(s)"
            
            # Signal Netdata to reload config
            if command -v netdatacli &> /dev/null; then
                netdatacli reload-claiming-state || true
            fi
        else
            rm "$temp_file"
        fi
    else
        # Remove config if no jobs found
        if [[ -f "$config_file" ]]; then
            rm "$config_file"
            log "Removed postgres.conf (no jobs found)"
        fi
        rm -f "$temp_file"
    fi
}

# Main loop
log "Starting Netdata config generator (poll interval: ${POLL_INTERVAL}s)"

while true; do
    generate_postgres_config
    sleep "$POLL_INTERVAL"
done
