services:
  cli-proxy-api:
    networks:
      - public
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.cli-proxy-api.rule: Host(`${CLI_PROXY_API_HOST}`)
        traefik.http.routers.cli-proxy-api.entrypoints: ${TRAEFIK_ROUTER_ENTRYPOINTS:-websecure}
        traefik.http.routers.cli-proxy-api.tls: ${TRAEFIK_ROUTER_TLS:-true}
        traefik.http.routers.cli-proxy-api.tls.certresolver: ${LETSENCRYPT_RESOLVER:-le}
        traefik.http.services.cli-proxy-api.loadbalancer.server.port: "8317"
        traefik.http.routers.cli-proxy-api.service: cli-proxy-api
networks:
  public:
    name: ${PUBLIC_NETWORK:-public}
    external: true
