config-version: 8
server:
  port: 8317
oauth:
  auth-dir: "/CLIProxyAPI/auth"
  providers:
    aistudio:
      ws-auth: true
management:
  allow-remote: true
  secret-key: ""
  panel-github-repository: https://github.com/router-for-me/Cli-Proxy-API-Management-Center
observability:
  usage:
    usage-statistics-enabled: true
  logs:
    logging-to-file: false
